# name: Deploy to ECR

# on:
 
#   push:
#     branches: [ main ]

# jobs:
  
#   build:
    
#     name: Build Image
#     runs-on: ubuntu-latest

   
#     steps:

#     - name: Check out code
#       uses: actions/checkout@v2
    
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

#     - name: Build, tag, and push image to Amazon ECR
#       run: |
#           docker build -t your-ecr-registry-uri/your-repo-name:${{ github.sha }} .
#           docker push your-ecr-registry-uri/your-repo-name:${{ github.sha }}


name: CI/CD with ECR and CodeArtifact

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and push Docker image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/testrun:${{ github.sha }} .
          docker push ${{ secrets.ECR_REGISTRY }}/testrun:${{ github.sha }}

      - name: Configure CodeArtifact authentication
        run: |
          aws codeartifact login --tool npm --repository testrunrepo --domain testrundomain

      - name: Install dependencies from CodeArtifact
        run: npm ci
