# name: Promote to Production

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   promote-to-prod:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check if PR is from develop to main
#         run: echo "PR from develop to main"
#         if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'

#       # - name: Notify for Approval
#       #   uses: actions/github-script@v5
#       #   with:
#       #     script: |
#       #       const { owner, repo } = context.repo;
#       #       const { data: pullRequests } = await octokit.rest.pulls.list({
#       #         owner,
#       #         repo,
#       #         state: 'closed',
#       #         base: 'main',
#       #       });

#       #       const latestPr = pullRequests[0];
#       #       const prUrl = latestPr.html_url;

#       #       console.log(`Please approve the promotion by reviewing the pull request: ${prUrl}`);
      
#       # - name: Wait for Approval
#       #   uses: actions/github-script@v5
#       #   with:
#       #     script: |
#       #       const { owner, repo, number } = context.issue;
#       #       await octokit.rest.pulls.requestReviewers({
#       #         owner,
#       #         repo,
#       #         pull_number: number,
#       #         reviewers: ['DeevineFayvour'],
#       #       });

#       #        console.log('Waiting for approval...');
#       #       await octokit.rest.pulls.checkIfMerged({
#       #         owner,
#       #         repo,
#       #         pull_number: number,
#       #       });

#       # - name: Bump Version and Create Release
#       #   run: |
#       #     npm install --save-dev standard-version
#       #     npx standard-version --first-release
#       #     git push --follow-tags origin main


#       - name: Copy Artifacts to Production
#         run: |
#           aws codeartifact copy-package-versions \
#             --domain testrundomain \
#             --source-repository for-dev \
#             --destination-repository for-prod 

name: Production CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI with your CodeArtifact credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Add your build and test steps here

      - name: Publish to prod repository
        run: |
          # Your code to publish artifacts to the prod repository
          # echo "Publishing artifacts to prod repository"
          aws codeartifact login --tool npm --for-prod --domain testrundomain
          npm install


